<?php

use Illuminate\Database\Seeder;

class WeightDistributionTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('weight_distribution')->insert([
            //For Role id=1 IC
            ['ksd_id' => '1', 'role_id' => '1', 'weight' => '12', 'proficiency_level' => '0.8'],
            ['ksd_id' => '2', 'role_id' => '1', 'weight' => '12', 'proficiency_level' => '2'],
            ['ksd_id' => '3', 'role_id' => '1', 'weight' => '3', 'proficiency_level' => '3'],
            ['ksd_id' => '4', 'role_id' => '1', 'weight' => '3', 'proficiency_level' => '2'],
            ['ksd_id' => '5', 'role_id' => '1', 'weight' => '6', 'proficiency_level' => '0'],
            ['ksd_id' => '6', 'role_id' => '1', 'weight' => '12', 'proficiency_level' => '2'],
            ['ksd_id' => '7', 'role_id' => '1', 'weight' => '12', 'proficiency_level' => '1'],
            ['ksd_id' => '8', 'role_id' => '1', 'weight' => '2.5', 'proficiency_level' => '3.5'],
            ['ksd_id' => '9', 'role_id' => '1', 'weight' => '2.5', 'proficiency_level' => '5'],
            ['ksd_id' => '11', 'role_id' => '1', 'weight' => '1', 'proficiency_level' => '0'],
            ['ksd_id' => '12', 'role_id' => '1', 'weight' => '1', 'proficiency_level' => '0'],
            ['ksd_id' => '13', 'role_id' => '1', 'weight' => '1', 'proficiency_level' => '0'],
            ['ksd_id' => '15', 'role_id' => '1', 'weight' => '1', 'proficiency_level' => '1'],
            ['ksd_id' => '16', 'role_id' => '1', 'weight' => '1', 'proficiency_level' => '1'],
            ['ksd_id' => '17', 'role_id' => '1', 'weight' => '1', 'proficiency_level' => '1'],
            ['ksd_id' => '18', 'role_id' => '1', 'weight' => '1', 'proficiency_level' => '0.7'],
            ['ksd_id' => '19', 'role_id' => '1', 'weight' => '1', 'proficiency_level' => '1'],
            ['ksd_id' => '20', 'role_id' => '1', 'weight' => '5', 'proficiency_level' => '1'],
            ['ksd_id' => '21', 'role_id' => '1', 'weight' => '5', 'proficiency_level' => '1'],
            ['ksd_id' => '23', 'role_id' => '1', 'weight' => '9', 'proficiency_level' => '1'],
            ['ksd_id' => '24', 'role_id' => '1', 'weight' => '1.5', 'proficiency_level' => '0'],
            ['ksd_id' => '25', 'role_id' => '1', 'weight' => '1.5', 'proficiency_level' => '1'],
            ['ksd_id' => '26', 'role_id' => '1', 'weight' => '6', 'proficiency_level' => '0.85'],
            ['ksd_id' => '27', 'role_id' => '1', 'weight' => '6', 'proficiency_level' => '0.85'],
            ['ksd_id' => '28', 'role_id' => '1', 'weight' => '4.5', 'proficiency_level' => '3'],
            ['ksd_id' => '29', 'role_id' => '1', 'weight' => '4.5', 'proficiency_level' => '2'],
            ['ksd_id' => '30', 'role_id' => '1', 'weight' => '2', 'proficiency_level' => '0.85'],
            ['ksd_id' => '31', 'role_id' => '1', 'weight' => '2', 'proficiency_level' => '0.9'],
            ['ksd_id' => '33', 'role_id' => '1', 'weight' => '2.5', 'proficiency_level' => '3.5'],
            ['ksd_id' => '34', 'role_id' => '1', 'weight' => '2.5', 'proficiency_level' => '5'],
            ['ksd_id' => '36', 'role_id' => '1', 'weight' => '1', 'proficiency_level' => '0'],
            ['ksd_id' => '37', 'role_id' => '1', 'weight' => '1', 'proficiency_level' => '0'],
            ['ksd_id' => '38', 'role_id' => '1', 'weight' => '1', 'proficiency_level' => '0'],
            ['ksd_id' => '40', 'role_id' => '1', 'weight' => '1', 'proficiency_level' => '1'],
            ['ksd_id' => '41', 'role_id' => '1', 'weight' => '1', 'proficiency_level' => '1'],
            ['ksd_id' => '42', 'role_id' => '1', 'weight' => '1', 'proficiency_level' => '1'],
            ['ksd_id' => '43', 'role_id' => '1', 'weight' => '1', 'proficiency_level' => '0.7'],
            ['ksd_id' => '44', 'role_id' => '1', 'weight' => '1', 'proficiency_level' => '1'],
            ['ksd_id' => '45', 'role_id' => '1', 'weight' => '5', 'proficiency_level' => '1'],
            ['ksd_id' => '46', 'role_id' => '1', 'weight' => '5', 'proficiency_level' => '1'],
            ['ksd_id' => '48', 'role_id' => '1', 'weight' => '2', 'proficiency_level' => '0.7'],
            ['ksd_id' => '51', 'role_id' => '1', 'weight' => '5', 'proficiency_level' => '3'],
            ['ksd_id' => '52', 'role_id' => '1', 'weight' => '5', 'proficiency_level' => '3'],
            ['ksd_id' => '53', 'role_id' => '1', 'weight' => '1', 'proficiency_level' => '0'],
            ['ksd_id' => '54', 'role_id' => '1', 'weight' => '1', 'proficiency_level' => '0'],
            ['ksd_id' => '55', 'role_id' => '1', 'weight' => '3', 'proficiency_level' => '0'],
            ['ksd_id' => '56', 'role_id' => '1', 'weight' => '3', 'proficiency_level' => '0'],
            ['ksd_id' => '58', 'role_id' => '1', 'weight' => '6', 'proficiency_level' => '1'],
            ['ksd_id' => '59', 'role_id' => '1', 'weight' => '9', 'proficiency_level' => '0'],
            ['ksd_id' => '60', 'role_id' => '1', 'weight' => '1', 'proficiency_level' => '0'],
            ['ksd_id' => '61', 'role_id' => '1', 'weight' => '1', 'proficiency_level' => '0'],
            

            //For Role id=2 Sr. IC
          ['ksd_id' => '1', 'role_id' => '2', 'weight' => '8', 'proficiency_level' => '0.9'],
            ['ksd_id' => '2', 'role_id' => '2', 'weight' => '8', 'proficiency_level' => '1'],
            ['ksd_id' => '3', 'role_id' => '2', 'weight' => '2', 'proficiency_level' => '4'],
            ['ksd_id' => '4', 'role_id' => '2', 'weight' => '2', 'proficiency_level' => '1'],
            ['ksd_id' => '5', 'role_id' => '2', 'weight' => '4', 'proficiency_level' => '0'],
            ['ksd_id' => '6', 'role_id' => '2', 'weight' => '8', 'proficiency_level' => '1'],
            ['ksd_id' => '7', 'role_id' => '2', 'weight' => '8', 'proficiency_level' => '2'],
            ['ksd_id' => '8', 'role_id' => '2', 'weight' => '7.5', 'proficiency_level' => '4'],
            ['ksd_id' => '9', 'role_id' => '2', 'weight' => '7.5', 'proficiency_level' => '3'],
            ['ksd_id' => '11', 'role_id' => '2', 'weight' => '2', 'proficiency_level' => '0'],
            ['ksd_id' => '12', 'role_id' => '2', 'weight' => '2', 'proficiency_level' => '3'],
            ['ksd_id' => '13', 'role_id' => '2', 'weight' => '2', 'proficiency_level' => '8'],
            ['ksd_id' => '15', 'role_id' => '2', 'weight' => '2', 'proficiency_level' => '2'],
            ['ksd_id' => '16', 'role_id' => '2', 'weight' => '2', 'proficiency_level' => '2'],
            ['ksd_id' => '17', 'role_id' => '2', 'weight' => '2', 'proficiency_level' => '3'],
            ['ksd_id' => '18', 'role_id' => '2', 'weight' => '2', 'proficiency_level' => '0.8'],
            ['ksd_id' => '19', 'role_id' => '2', 'weight' => '2', 'proficiency_level' => '1'],
            ['ksd_id' => '20', 'role_id' => '2', 'weight' => '5', 'proficiency_level' => '1'],
            ['ksd_id' => '21', 'role_id' => '2', 'weight' => '5', 'proficiency_level' => '1'],
            ['ksd_id' => '23', 'role_id' => '2', 'weight' => '6', 'proficiency_level' => '3'],
            ['ksd_id' => '24', 'role_id' => '2', 'weight' => '1', 'proficiency_level' => '1'],
            ['ksd_id' => '25', 'role_id' => '2', 'weight' => '1', 'proficiency_level' => '2'],
            ['ksd_id' => '26', 'role_id' => '2', 'weight' => '4', 'proficiency_level' => '0.9'],
            ['ksd_id' => '27', 'role_id' => '2', 'weight' => '4', 'proficiency_level' => '0.9'],
            ['ksd_id' => '28', 'role_id' => '2', 'weight' => '3', 'proficiency_level' => '4'],
            ['ksd_id' => '29', 'role_id' => '2', 'weight' => '3', 'proficiency_level' => '3'],
            ['ksd_id' => '30', 'role_id' => '2', 'weight' => '1.3', 'proficiency_level' => '0.9'],
            ['ksd_id' => '31', 'role_id' => '2', 'weight' => '1.3', 'proficiency_level' => '0.95'],
            ['ksd_id' => '33', 'role_id' => '2', 'weight' => '7.5', 'proficiency_level' => '4'],
            ['ksd_id' => '34', 'role_id' => '2', 'weight' => '7.5', 'proficiency_level' => '3'],
            ['ksd_id' => '36', 'role_id' => '2', 'weight' => '2', 'proficiency_level' => '0'],
            ['ksd_id' => '37', 'role_id' => '2', 'weight' => '2', 'proficiency_level' => '3'],
            ['ksd_id' => '38', 'role_id' => '2', 'weight' => '2', 'proficiency_level' => '8'],
            ['ksd_id' => '40', 'role_id' => '2', 'weight' => '2', 'proficiency_level' => '2'],
            ['ksd_id' => '41', 'role_id' => '2', 'weight' => '2', 'proficiency_level' => '2'],
            ['ksd_id' => '42', 'role_id' => '2', 'weight' => '2', 'proficiency_level' => '3'],
            ['ksd_id' => '43', 'role_id' => '2', 'weight' => '2', 'proficiency_level' => '0.8'],
            ['ksd_id' => '44', 'role_id' => '2', 'weight' => '2', 'proficiency_level' => '1'],
            ['ksd_id' => '45', 'role_id' => '2', 'weight' => '5', 'proficiency_level' => '2'],
            ['ksd_id' => '46', 'role_id' => '2', 'weight' => '5', 'proficiency_level' => '1'],
            ['ksd_id' => '48', 'role_id' => '2', 'weight' => '1.3', 'proficiency_level' => '0.8'],
            ['ksd_id' => '51', 'role_id' => '2', 'weight' => '5', 'proficiency_level' => '3'],
            ['ksd_id' => '52', 'role_id' => '2', 'weight' => '5', 'proficiency_level' => '3'],
            ['ksd_id' => '53', 'role_id' => '2', 'weight' => '2', 'proficiency_level' => '1'],
            ['ksd_id' => '54', 'role_id' => '2', 'weight' => '2', 'proficiency_level' => '1'],
            ['ksd_id' => '55', 'role_id' => '2', 'weight' => '2', 'proficiency_level' => '1'],
            ['ksd_id' => '56', 'role_id' => '2', 'weight' => '2', 'proficiency_level' => '0'],
            ['ksd_id' => '58', 'role_id' => '2', 'weight' => '4', 'proficiency_level' => '1'],
            ['ksd_id' => '59', 'role_id' => '2', 'weight' => '6', 'proficiency_level' => '0'],
            ['ksd_id' => '60', 'role_id' => '2', 'weight' => '2', 'proficiency_level' => '0'],
            ['ksd_id' => '61', 'role_id' => '2', 'weight' => '2', 'proficiency_level' => '0'],


            //For Role id=3 Team Lead
            ['ksd_id' => '1', 'role_id' => '3', 'weight' => '6', 'proficiency_level' => '0.95'],
            ['ksd_id' => '2', 'role_id' => '3', 'weight' => '6', 'proficiency_level' => '0'],
            ['ksd_id' => '3', 'role_id' => '3', 'weight' => '1.5', 'proficiency_level' => '5'],
            ['ksd_id' => '4', 'role_id' => '3', 'weight' => '1.5', 'proficiency_level' => '0'],
            ['ksd_id' => '5', 'role_id' => '3', 'weight' => '3', 'proficiency_level' => '0'],
            ['ksd_id' => '6', 'role_id' => '3', 'weight' => '6', 'proficiency_level' => '0'],
            ['ksd_id' => '7', 'role_id' => '3', 'weight' => '6', 'proficiency_level' => '3'],
            ['ksd_id' => '8', 'role_id' => '3', 'weight' => '10', 'proficiency_level' => '4.5'],
            ['ksd_id' => '9', 'role_id' => '3', 'weight' => '10', 'proficiency_level' => '0'],
            ['ksd_id' => '11', 'role_id' => '3', 'weight' => '2.5', 'proficiency_level' => '0'],
            ['ksd_id' => '12', 'role_id' => '3', 'weight' => '2.5', 'proficiency_level' => '3'],
            ['ksd_id' => '13', 'role_id' => '3', 'weight' => '2.5', 'proficiency_level' => '10'],
            ['ksd_id' => '15', 'role_id' => '3', 'weight' => '2.5', 'proficiency_level' => '3'],
            ['ksd_id' => '16', 'role_id' => '3', 'weight' => '2.5', 'proficiency_level' => '3'],
            ['ksd_id' => '17', 'role_id' => '3', 'weight' => '2.5', 'proficiency_level' => '3'],
            ['ksd_id' => '18', 'role_id' => '3', 'weight' => '2.5', 'proficiency_level' => '1'],
            ['ksd_id' => '19', 'role_id' => '3', 'weight' => '2.5', 'proficiency_level' => '1'],
            ['ksd_id' => '20', 'role_id' => '3', 'weight' => '5', 'proficiency_level' => '2'],
            ['ksd_id' => '21', 'role_id' => '3', 'weight' => '5', 'proficiency_level' => '1'],
            ['ksd_id' => '23', 'role_id' => '3', 'weight' => '4.5', 'proficiency_level' => '6'],
            ['ksd_id' => '24', 'role_id' => '3', 'weight' => '0.75', 'proficiency_level' => '1'],
            ['ksd_id' => '25', 'role_id' => '3', 'weight' => '0.75', 'proficiency_level' => '3'],
            ['ksd_id' => '26', 'role_id' => '3', 'weight' => '3', 'proficiency_level' => '1'],
            ['ksd_id' => '27', 'role_id' => '3', 'weight' => '3', 'proficiency_level' => '1'],
            ['ksd_id' => '28', 'role_id' => '3', 'weight' => '2.25', 'proficiency_level' => '5'],
            ['ksd_id' => '29', 'role_id' => '3', 'weight' => '2.25', 'proficiency_level' => '4'],
            ['ksd_id' => '30', 'role_id' => '3', 'weight' => '1', 'proficiency_level' => '1'],
            ['ksd_id' => '31', 'role_id' => '3', 'weight' => '1', 'proficiency_level' => '1'],
            ['ksd_id' => '33', 'role_id' => '3', 'weight' => '10', 'proficiency_level' => '4.5'],
            ['ksd_id' => '34', 'role_id' => '3', 'weight' => '10', 'proficiency_level' => '0'],
            ['ksd_id' => '36', 'role_id' => '3', 'weight' => '2.5', 'proficiency_level' => '0'],
            ['ksd_id' => '37', 'role_id' => '3', 'weight' => '2.5', 'proficiency_level' => '3'],
            ['ksd_id' => '38', 'role_id' => '3', 'weight' => '2.5', 'proficiency_level' => '10'],
            ['ksd_id' => '40', 'role_id' => '3', 'weight' => '2.5', 'proficiency_level' => '3'],
            ['ksd_id' => '41', 'role_id' => '3', 'weight' => '2.5', 'proficiency_level' => '3'],
            ['ksd_id' => '42', 'role_id' => '3', 'weight' => '2.5', 'proficiency_level' => '3'],
            ['ksd_id' => '43', 'role_id' => '3', 'weight' => '2.5', 'proficiency_level' => '1'],
            ['ksd_id' => '44', 'role_id' => '3', 'weight' => '2.5', 'proficiency_level' => '1'],
            ['ksd_id' => '45', 'role_id' => '3', 'weight' => '5', 'proficiency_level' => '2'],
            ['ksd_id' => '46', 'role_id' => '3', 'weight' => '5', 'proficiency_level' => '1'],
            ['ksd_id' => '48', 'role_id' => '3', 'weight' => '1', 'proficiency_level' => '1'],
            ['ksd_id' => '51', 'role_id' => '3', 'weight' => '5', 'proficiency_level' => '3'],
            ['ksd_id' => '52', 'role_id' => '3', 'weight' => '5', 'proficiency_level' => '3'],
            ['ksd_id' => '53', 'role_id' => '3', 'weight' => '2.5', 'proficiency_level' => '1'],
            ['ksd_id' => '54', 'role_id' => '3', 'weight' => '2.5', 'proficiency_level' => '1'],
            ['ksd_id' => '55', 'role_id' => '3', 'weight' => '1.5', 'proficiency_level' => '2'],
            ['ksd_id' => '56', 'role_id' => '3', 'weight' => '1.5', 'proficiency_level' => '0'],
            ['ksd_id' => '58', 'role_id' => '3', 'weight' => '3', 'proficiency_level' => '1'],
            ['ksd_id' => '59', 'role_id' => '3', 'weight' => '4.5', 'proficiency_level' => '0'],
            ['ksd_id' => '60', 'role_id' => '3', 'weight' => '2.5', 'proficiency_level' => '0.9'],
            ['ksd_id' => '61', 'role_id' => '3', 'weight' => '2.5', 'proficiency_level' => '0.9'],
        ]);
    }    
}
